### ISSUE TITLE
PIC X and PIC X(01) are not the same

### ISSUE THREAD

**Issue by maxime645** [TypeCobolTeam/TypeCobol#1253] opened 2019-01-30 16:10 UTC
**Describe the bug**
The given parameters of a procedure does not match the expected one, even if they are

**To Reproduce**
(Type)Cobol code that cause the bug : (if any)
```cobol
       IDENTIFICATION division.
       PROGRAM-ID. MyPGM.
       data division.
       working-storage section.
      
       01 StringBuilder typedef strict public PIC X(5).
      
       01 TextWriter  typedef strict public.
           05 sBuilder        type StringBuilder.
      
      
       01 buffer pic X.
       01 blen     pic S9(5) comp-5.
      
       01 tw        TYPE TextWriter.
      
       procedure division.
      
       INIT-LIBRARY.
      
           call Append
                    INPUT  buffer
                           blen
                    in-out tw::sBuilder
                    .
           goback.
      
      *================================================================
       declare procedure Append public
           input    src    pic X(01)
                    sz     pic S9(5) comp-5
           in-out   sb  type StringBuilder
           .
       end-declare.
      
       end program MyPGM.
```
The following error is thrown :

> Syntax error : Function 'Append' expected parameter 'src' with picture X(01) and received 'buffer' with picture X

**Expected behavior**
PIC X and PIC X(01) are the same, there shouldn't be any error

**Comment by smedilol** [comment] 2019-02-01 13:56
Duplicate of #1090.
Although I'll copy your example.

**Closed by smedilol** 2019-02-01 13:56 UTC
