### ISSUE TITLE
Bug with EI Legacy Remarks

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#431] opened 2017-02-17 09:14 UTC
EI Legacy Remarks doesn't seems to works on our private tests

**Comment by collarbe** [comment] 2017-02-17 13:14
Remarks Scanner fails on that kind of declaration : 

*REMARKS.                              
*         COPY=YAUCAUL
*         COPY=YAUCPR0

**Comment by collarbe** [comment] 2017-02-17 13:58
Also notice a bug with "," character. Fixed in future commit

**Comment by collarbe** [comment] 2017-02-17 14:04
Do we have to maage this kind of case ? (bug caused by * after REMARKS.) 
FIle COMBMTIE.PGM
000330*REMARKS.                                                        *****0000000

**Comment by collarbe** [comment] 2017-02-17 15:03
Known Erros Listing : 

Absent COPY
YPRFEDI
YDEPSCH
YIODIDO
YEPLPGM
YORLTRA
YORLSPI
YEPLCTN
MCEUI06
YGBRDA1
YGBRDE9
YGBRDA4
YGBRDA5
YGBRPRI
YGBRFD1
YGBRCCO
YGAR42B
YGAR34B
YGARALE
YGARFRE
YGARCTR
YICCEPR
YICCSPR
YIDC602
YIDC102
TIDOCTR
YIDOPTI
YIPCWRK
YIPCZCO
YIDXTAU
YIPIOCA
YIDPASS
YIDPSTA
YIDPTAM
YPRTD20
YPRTD01
YDACCAL
YTHMDB2
YTPLIAT
YGTEES1
YACMPC1
YASSRA2
YADP1AT
YASUAS5
YCBRENR
YCARDEN
YCOPDBQ
YSALECG
YCCTVDX
YCCTINV
YCDIMIN



Reading Remarks Copy Errors 
AUCBAUC2.PGM 	COPY = ….
AUCBDEP1.PGM 	COPY = ….
AUCBIM20.PGM 	COPY = ….
AUCLAPR2.PGM 	COPY = ….
ID2TI015.PGM 	COPY = ….
IDCBACN3.PGM 	COPY = ….
IDCTL003.PGM 	COPY = ….
IDCMARD0.PGM 	COPY name too long (YI03PCB75)

ADPFSPCB.PGM 	COPY name too long (YACMPCB10)

ADPWIPAP.PGM 	COPY name too long (YACMPCB10)

RDIMEDTL.PGM 	? ? ==> Symbol /!\

SEVTPLIA.PGM 	Double comment ** line 55

**Closed** 2017-02-20 08:24 UTC
Labels: bug, Cobol
