### ISSUE TITLE
Codegen: action Expand to a different Node doesn't move comment, debug, compilerDirective

### ISSUE THREAD

**Issue by osmedile** [TypeCobolTeam/TypeCobol#319] opened 2016-10-16 22:08 UTC
TypeCobol function and procedure use the action "expand" of Codegen to move Nodes to a new parent.

Example:

``` cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZDATE.
       PROCEDURE DIVISION.
       DECLARE FUNCTION currentDate PUBLIC
000000*Comment 1
           RETURNING Result TYPE date.
000000*Comment 2
       PROCEDURE DIVISION.
000000*Comment 3
           REPLACE ==:toto:== by ==titi==.
           ACCEPT Result FROM DATE YYYYMMDD
           .
       END-DECLARE.
       END PROGRAM DVZZDAT.
```

The generated code is :

``` cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZZDATE.
       PROCEDURE DIVISION.
           SET currentDate TO ENTRY 'F0000001'   
*=================================================================
      *DECLARE FUNCTION currentDate PUBLIC                                    
000000*Comment 1
      *    RETURNING Result TYPE date.                                        
000000*Comment 2
000000*Comment 3
      *_________________________________________________________________
       END PROGRAM DVZZDAT.
      *_________________________________________________________________      
       IDENTIFICATION DIVISION.                                               
       PROGRAM-ID. F0000001.                                                  
       DATA DIVISION.                                                         
       LINKAGE SECTION.                                                       
       01 Result.                                                             
           02 YYYY PIC 9(4).                                                  
           02 MM PIC 9(2).                                                    
           02 DD PIC 9(2).                                                    
       PROCEDURE DIVISION                                                     
             USING BY REFERENCE Result                                        
           .                                                                  
           ACCEPT Result FROM DATE YYYYMMDD
           .
       END PROGRAM F0000001.                                 
```

The comment stayed in the original function Node which has been commented (and it's original children removed).
Comment1 can stay like this. We need to discuss about Comment2. But Comment3 must be copied in the procedure division of PROGRAM F0000001. 

This problem also concern Debug lines and Compiler directives. Although currently compiler directives are lost when generating the code.

**Comment by smedilol** [comment] 2016-12-28 14:04
DUPLICATE OF #292

**Closed by smedilol** 2016-12-28 14:04 UTC
Labels: bug, Codegen, Functions, TypeCobol
