### ISSUE TITLE
PREPARE Statement

### ISSUE THREAD

**Issue by laabidiHend** [TypeCobolTeam/TypeCobol#2292] opened 2022-07-15 09:59 UTC
Description

The [Prepare](https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-prepare) Statement creates an executable SQL statement from a string form of the statement. The character-string form is called a statement string. The executable form is called a prepared statement.
This implies:

To write the ANTLR grammar
To write the CUP grammar
Building the Prepare Statement CodeElement
Building the PrepareNode
Creating the corresponding Sql Object
Making corresponding CodeElement, Node and SqlObject classes visitable
Write test unit

**Comment by smedilol** [comment] 2022-07-18 10:57
Duplicate of #2279

**Closed by smedilol** 2022-07-18 10:57 UTC
Labels: SQL Parser
