### ISSUE TITLE
Functions declaration: codegen

### ISSUE THREAD

**Issue by wiztigers** [TypeCobolTeam/TypeCobol#257] opened 2016-07-11 13:58 UTC
**CHILD ISSUE OF #245**
Make function declarations be generated as nested programs in output file.

**Comment by wiztigers** [comment] 2016-07-12 10:52
b5c7abdcfe4eb37ca13a29cc2ee53d6a0cefac77 bae7170ba0fbf8e1fef8fe9e80f06ea107aaff4e Done.
But I don't have any specification for Procedures codegen. @smedilol, as RETURNING clause only accepts one subject, how should it be done?

**Comment by smedilol** [comment] 2016-09-21 08:30
Current issue was only about the new TC syntax.
Specifications about CodeGen will come into a new issue.

**Comment by smedilol** [comment] 2016-09-21 15:27
Duplicate of #278

**Closed by smedilol** 2016-09-21 15:27 UTC
Labels: enhancement, Functions, rfc
