### ISSUE TITLE
Visit Affectations in derivates of AbstractArithmeticStatement and Rounded expressions

### ISSUE THREAD

**Issue by delevoye** [TypeCobolTeam/TypeCobol#1969] opened 2021-05-21 15:56 UTC
Expressions in derivates of `AbstractArithmeticStatement` are not visited, especially Expressions contained in the field `Affectations`.
These Expressions are created by the parser, but are not explicit Expressions in the code. Visiting them would allow to have analysis on them for example.

Example:
```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.  Pgm.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 X                    PIC 9.
       01 Y                    PIC 9.
       01 Z                    PIC 9.
       PROCEDURE DIVISION.
      * Only variable Z is visited and not the rounded expression
           COMPUTE X ROUNDED = Z
      * Nothing is visited
           ADD Y TO X ROUNDED
           SUBTRACT Y FROM X ROUNDED
           MULTIPLY Y BY Z GIVING X ROUNDED
           DIVIDE Y BY Z GIVING X ROUNDED
      
           GOBACK
           .      
       END PROGRAM Pgm.
```

**Comment by fm-117** [comment] 2021-05-27 12:50
This is definitely by design.

As you noticed, these expressions are created by the parser but do not correspond to an actual expression written in code. They are used to represent internally what is written into variable(s). As for the rounded, all inheritors pass the information in one form or anotherr (either a `RoundedResult`  instance or a boolean syntax proprerty).

I suggest to close this issue, @rooksdo, @mayanje do you agree ?

**Comment by rooksdo** [comment] 2021-06-07 13:41
Agreed with @fm-117's explanation.

**Closed** 2021-06-25 06:42 UTC
Labels: Cobol, Enhancement, rfc
