### ISSUE TITLE
Completion should be able to suggest children compatible variable

### ISSUE THREAD

**Issue by collarbe** [TypeCobolTeam/TypeCobol#1082] opened 2018-08-07 11:28 UTC
In the following case : 

```COBOL
01 ArrayDesc.
  05 var1 PIC 9.
  05 var2 PIC 9.

MOVE 1 TO ...
```

The completion does not suggest variable like `ArrayDesc::var1` or `ArrayDesc::var2`. It could be great, but it has to be discuss, this solution may suggest all the numeric varaible available.. it would be to much.

**Comment by smedilol** [comment] 2019-03-29 10:25
duplicate of #907

**Closed by smedilol** 2019-03-29 10:25 UTC
Labels: Enhancement, Language Server Protocol, User Visible, rfc
