### ISSUE TITLE
Review the auto dependencies loading by FileWatcher

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1500] opened 2019-10-10 15:37 UTC
This issue is to ensure that using the TypeCobolLanguageServer, the auto dependencies loading mechanism by FileWatchers uses the right TypeCobol plugin configurations and options.
This for instances for Copybook concatenation.

**Comment by smedilol** [comment] 2019-10-18 13:54
Following  #1427 it seems now ok.

**Comment by smedilol** [comment] 2019-11-13 16:25
Following our meeting of 2019/11/12, the dependencies are now loaded correctly.
But sometimes it can takes time for the FileWatcher to receive an event about a folder change.

We can improve this behavior when an user make an export and then except the folder to be refreshed.
We could create a notification in LS so RDZ client can ask a dependencies folder refresh.

**Comment by smedilol** [comment] 2019-11-13 16:26
I'll postpone this issue to next milestone because we need more feedback from our users. We must also wait fro 1.4 to be released.

**Comment by smedilol** [comment] 2019-12-05 15:51
With #1427 now merged, the problem is fixed.

**Closed by smedilol** 2019-12-05 15:51 UTC
Labels: Language Server Protocol, TypeCobol
